spring:
  # 数据源配置项
  datasource:
    url: jdbc:mysql://localhost:3306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zhuyang
  # Spring Cloud 配置项
  cloud:
    nacos:
      # Spring Cloud Nacos Discovery 配置项
      discovery:
        server-addr: localhost:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间

# Dubbo 配置项
dubbo:
  # Dubbo 注册中心
  registry:
    #    address: spring-cloud://localhost:8848 # 指定 Dubbo 服务注册中心的地址
    address: nacos://localhost:8848?namespace=dev # 指定 Dubbo 服务注册中心的地址
